global:
    splunk:
        hec:
            host: ENC[AES256_GCM,data:PAI+kiGEbPY6Q5qU9F2J,iv:0mhXMJhChSjQasTYrL4aPZ5jXhkTEeQIKcDoOk+OaJA=,tag:4Z1JqbHdKhr3nPQh7YgAsg==,type:str]
            port: 8088
            token: ENC[AES256_GCM,data:hX1CKLSsDasRMypC3SpQYtQBCGepHAH478pb0DtZbIUskycY,iv:KW/ds9E83hQrS6REWP1L5uPkChm7UBdqkBcJOCQa5TA=,tag:TCoYQAQXJiFYFEfKkuOofg==,type:str]
            protocol: http
            indexName: main
            
splunk-kubernetes-logging:
  enabled: true

  fluentd:
    # path of logfiles, default /var/log/containers/*.log
    path: /var/log/containers/*.log
    # paths of logfiles to exclude. object type is array as per fluentd specification:
    # https://docs.fluentd.org/input/tail#exclude_path
    exclude_path:
      - /var/log/containers/kube-svc-redirect*.log
      - /var/log/containers/splunk*.log
      - /var/log/containers/*_kube-system_*.log
      - /var/log/containers/kube-flannel*.log
  rbac:
    create: true

  serviceAccount:
    create: true


  # Exclude Splunk/Fluentd logs to avoid ingestion loops
  containers:
    logFormatType: cri

splunk-kubernetes-metrics:
  enabled: false  # Deprecated

splunk-kubernetes-objects:
  enabled: false  # Deprecated
